[package]
name = "fcs_flim"
version = "0.1.0"
edition = "2021"

[lib]
name = "fcs_flim"

[dependencies]
pyo3 = { version = "0.21.2" , features = ["extension-module"] }
rand = "0.8.4"
rayon = "1.10.0"
ndarray = "0.15.6"
num-traits = "0.2.18"
nalgebra = "0.32.5"
decimal = "2.1.0"