[package]
name = "fcs_flim"
version = "0.1.0"
edition = "2021"

[lib]
name = "fcs_flim"

[dependencies]
pyo3 = { version = "0.21.2" , features = ["extension-module"] }
rayon = "1.10.0"
nalgebra = "0.32.5"